### ISSUE TITLE
Things to learn about

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/summit-2023#22]
It came up during multiple pre-summit meetings, that it would be nice to have knowledge transfer sessions.

Please comment topic suggestions in this issue.

**Comment by bsipocz** [comment]
@jarrodmillman mentioned the topics of writing github actions

**Comment by bsipocz** [comment]
@bsipocz hopes @henryiii will showcase composite actions

**Comment by pllim** [comment]
@pllim hopes to learn how https://scikit-hep.org/developer/reporeview (@henryiii) really works and how to adopt it for another project with different requirements. Also see https://github.com/astropy/astropy-project/issues/334 .
